import React, { useMemo, useState } from 'react';
import { ArrowRight, BriefcaseBusiness, Check, ContactRound, CreditCard, Pencil, Phone, Plus, Trash2, UserRound, WalletCards, X } from 'lucide-react';
import { SectionGuide } from '../components/SectionGuide';
import { ConfirmDialog, ConfirmRequest } from '../components/ConfirmDialog';
import { JalaliDatePicker } from '../components/JalaliDatePicker';
import { ColleagueEntry, deleteColleague, getColleagues, saveColleague, StudioMemberEntry, MemberLedgerEntry, LedgerService, LedgerTransaction, deleteStudioMember, getMemberLedgers, getStudioMembers, saveMemberLedger, saveStudioMember } from '../services/storage';
import { pickPhoneFromContacts } from '../services/contactPicker';
import { gregorianToJalali, jalaliToIso, JalaliDate, todayJalali, isoToJalaliLabel } from '../services/jalali';

const SPECIALTIES = ['کرین', 'هلی شات', 'رونین', 'تدوینگر', 'آتلیه‌دار', 'دوربین ثابت', 'FPV', 'فیلم‌بردار', 'عکاس', 'سایرم'];
const LEDGER_SERVICES = ['کرین', 'هلی شات', 'رونین', 'دوربین ثابت', 'تدوینگر', 'عکاس', 'سرویس', 'پخش پروجکشن', 'TV'];
const money = (n: number) => n.toLocaleString('fa-IR');
const parseMoney = (v: string) => Number(v.replace(/[^0-9]/g, '')) || 0;
const moneyInput = (n: number) => n ? money(n) : '';
const isoJ = (iso: string): JalaliDate => { const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(iso || ''); return m ? gregorianToJalali(+m[1], +m[2], +m[3]) : todayJalali(); };
const colleagueBlank = () => ({ name: '', phone: '', specialties: [] as string[], otherSpecialty: '' });
const memberBlank = () => ({ name: '', phone: '', role: '' });

type Tab = 'colleagues' | 'members';
export const ColleaguesView: React.FC = () => {
  const [tab, setTab] = useState<Tab>('colleagues');
  const [colleagues, setColleagues] = useState<ColleagueEntry[]>(getColleagues());
  const [members, setMembers] = useState<StudioMemberEntry[]>(getStudioMembers());
  const [ledger, setLedger] = useState<MemberLedgerEntry[]>(getMemberLedgers());
  const [editingColleague, setEditingColleague] = useState<ColleagueEntry | null>(null);
  const [colleagueDraft, setColleagueDraft] = useState(colleagueBlank());
  const [editingMember, setEditingMember] = useState<StudioMemberEntry | null>(null);
  const [memberDraft, setMemberDraft] = useState(memberBlank());
  const [openMemberId, setOpenMemberId] = useState<string | null>(null);
  const [ledgerForm, setLedgerForm] = useState<{ eventName: string; date: string; services: LedgerService[]; transactions: LedgerTransaction[] }>({ eventName: '', date: jalaliToIso(todayJalali()), services: [], transactions: [] });
  const [transaction, setTransaction] = useState<{ type: 'paid' | 'credit'; amount: string; note: string; date: string }>({ type: 'paid', amount: '', note: '', date: jalaliToIso(todayJalali()) });
  const [confirm, setConfirm] = useState<ConfirmRequest | null>(null);
  const [contactMessage, setContactMessage] = useState('');
  const updateColleague = (key: keyof ReturnType<typeof colleagueBlank>, value: any) => setColleagueDraft(x => ({ ...x, [key]: value }));
  const updateMember = (key: keyof ReturnType<typeof memberBlank>, value: string) => setMemberDraft(x => ({ ...x, [key]: value }));
  const chooseContact = async (target: 'colleague' | 'member') => { const phone = await pickPhoneFromContacts(); if (phone) { target === 'colleague' ? updateColleague('phone', phone) : updateMember('phone', phone); setContactMessage('شماره از مخاطبین انتخاب شد.'); } else setContactMessage('انتخاب مخاطب در این دستگاه در دسترس نیست؛ شماره را دستی وارد کن.'); };
  const saveColleagueForm = (e: React.FormEvent) => { e.preventDefault(); if (!colleagueDraft.name.trim() || !colleagueDraft.phone.trim()) return; const now = Date.now(); const item: ColleagueEntry = { ...colleagueDraft, name: colleagueDraft.name.trim(), phone: colleagueDraft.phone.trim(), otherSpecialty: colleagueDraft.otherSpecialty.trim(), id: editingColleague?.id || `colleague-${now}`, createdAt: editingColleague?.createdAt || now, updatedAt: now }; if (saveColleague(item).ok) { setColleagues(getColleagues()); setEditingColleague(null); setColleagueDraft(colleagueBlank()); } };
  const saveMemberForm = (e: React.FormEvent) => { e.preventDefault(); if (!memberDraft.name.trim() || !memberDraft.phone.trim()) return; const now = Date.now(); const item: StudioMemberEntry = { ...memberDraft, name: memberDraft.name.trim(), phone: memberDraft.phone.trim(), role: memberDraft.role.trim(), id: editingMember?.id || `member-${now}`, createdAt: editingMember?.createdAt || now, updatedAt: now }; if (saveStudioMember(item).ok) { setMembers(getStudioMembers()); setEditingMember(null); setMemberDraft(memberBlank()); } };
  const remove = (kind: 'colleague' | 'member', id: string, name: string) => setConfirm({ title: `حذف ${kind === 'member' ? 'عضو آتلیه' : 'همکار'}`, text: `«${name}» حذف شود؟`, confirmLabel: 'حذف', tone: 'danger', icon: Trash2, onConfirm: () => { if (kind === 'member') { deleteStudioMember(id); setMembers(getStudioMembers()); setLedger(getMemberLedgers()); } else { deleteColleague(id); setColleagues(getColleagues()); } } });
  const openLedger = (member: StudioMemberEntry) => { setOpenMemberId(member.id); setLedgerForm({ eventName: '', date: jalaliToIso(todayJalali()), services: [], transactions: [] }); };
  const toggleService = (name: string) => setLedgerForm(x => ({ ...x, services: x.services.some(s => s.name === name) ? x.services.filter(s => s.name !== name) : [...x.services, { name, amount: 0 }] }));
  const updateServiceAmount = (name: string, value: string) => setLedgerForm(x => ({ ...x, services: x.services.map(s => s.name === name ? { ...s, amount: parseMoney(value) } : s) }));
  const addTransaction = () => { const amount = parseMoney(transaction.amount); if (!amount) return; setLedgerForm(x => ({ ...x, transactions: [...x.transactions, { id: `tx-${Date.now()}`, type: transaction.type, amount, note: transaction.note.trim(), date: transaction.date }] })); setTransaction({ type: 'paid', amount: '', note: '', date: jalaliToIso(todayJalali()) }); };
  const saveLedger = () => { if (!openMemberId || !ledgerForm.eventName.trim() || !ledgerForm.services.length) return; const now = Date.now(); const item: MemberLedgerEntry = { id: `ledger-${now}`, memberId: openMemberId, eventName: ledgerForm.eventName.trim(), date: ledgerForm.date, services: ledgerForm.services, transactions: ledgerForm.transactions, createdAt: now, updatedAt: now }; if (saveMemberLedger(item).ok) { setLedger(getMemberLedgers()); setOpenMemberId(null); } };
  const openMember = members.find(x => x.id === openMemberId);
  const memberLedgers = useMemo(() => openMemberId ? ledger.filter(x => x.memberId === openMemberId) : [], [ledger, openMemberId]);
  return <div className="space-y-4"><SectionGuide section="colleagues" title="همکارانم" text="همکاران بیرونی و اعضای ثابت آتلیه را جدا نگه دار و حساب هر اجرا را ثبت کن." />
    <div className="flex gap-1.5 rounded-[20px] bg-surface2 p-1.5"><button onClick={() => setTab('colleagues')} className={`flex-1 rounded-[15px] min-h-11 text-[12px] font-extrabold ${tab === 'colleagues' ? 'bg-olive text-paper' : 'text-muted'}`}>همکاران بیرونی</button><button onClick={() => setTab('members')} className={`flex-1 rounded-[15px] min-h-11 text-[12px] font-extrabold ${tab === 'members' ? 'bg-olive text-paper' : 'text-muted'}`}>اعضای آتلیه</button></div>
    {tab === 'colleagues' ? <ColleaguesPanel items={colleagues} editing={editingColleague} draft={colleagueDraft} update={updateColleague} onSave={saveColleagueForm} onStart={() => { setEditingColleague(null); setColleagueDraft(colleagueBlank()); }} onEdit={(x) => { setEditingColleague(x); setColleagueDraft({ name: x.name, phone: x.phone, specialties: x.specialties, otherSpecialty: x.otherSpecialty || '' }); }} onDelete={(x) => remove('colleague', x.id, x.name)} chooseContact={() => chooseContact('colleague')} contactMessage={contactMessage} /> : <MembersPanel members={members} editing={editingMember} draft={memberDraft} update={updateMember} onSave={saveMemberForm} onStart={() => { setEditingMember(null); setMemberDraft(memberBlank()); }} onEdit={(x) => { setEditingMember(x); setMemberDraft({ name: x.name, phone: x.phone, role: x.role }); }} onDelete={(x) => remove('member', x.id, x.name)} chooseContact={() => chooseContact('member')} contactMessage={contactMessage} onLedger={openLedger} />}
    {openMember && <LedgerSheet member={openMember} form={ledgerForm} setForm={setLedgerForm} transaction={transaction} setTransaction={setTransaction} toggleService={toggleService} updateServiceAmount={updateServiceAmount} addTransaction={addTransaction} save={saveLedger} close={() => setOpenMemberId(null)} previous={memberLedgers} />}
    <ConfirmDialog request={confirm} onClose={() => setConfirm(null)} />
  </div>;
};

const ContactField: React.FC<{ label: string; value: string; onChange: (v: string) => void; onContact: () => void }> = ({ label, value, onChange, onContact }) => <div><span className="label">{label}</span><div className="flex gap-2"><input className="field min-w-0 flex-1" type="tel" value={value} onChange={e => onChange(e.target.value)} placeholder="0912..." required /><button type="button" onClick={onContact} className="icon-button shrink-0" title="انتخاب از مخاطبین"><ContactRound className="w-4 h-4" /></button></div></div>;
const TextField: React.FC<{ label: string; value: string; onChange: (v: string) => void; placeholder?: string }> = ({ label, value, onChange, placeholder }) => <label className="block"><span className="label">{label}</span><input className="field" value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} required /></label>;
const ColleaguesPanel: React.FC<any> = ({ items, editing, draft, update, onSave, onStart, onEdit, onDelete, chooseContact, contactMessage }) => <section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="text-[15px] font-extrabold">لیست همکاران</h2><p className="mt-1 text-[10px] text-muted">{items.length.toLocaleString('fa-IR')} همکار</p></div>{!editing && <button onClick={onStart} className="btn btn-primary !px-3 !py-2 !text-[11px]"><Plus className="w-4 h-4" /> همکار جدید</button>}</div>{editing || items.length === 0 ? <form onSubmit={onSave} className="affiche-form card space-y-4 p-4"><div className="form-heading"><span className="form-heading-icon"><BriefcaseBusiness className="w-5 h-5" /></span><div><h2 className="text-[16px] font-extrabold">{editing ? 'ویرایش همکار' : 'همکار جدید'}</h2><p className="mt-1 text-[10px] text-muted">اطلاعات تماس و تخصص</p></div></div><TextField label="نام همکار" value={draft.name} onChange={(v: string) => update('name', v)} placeholder="مثلاً علی حاتمی" /><ContactField label="شماره تماس" value={draft.phone} onChange={(v) => update('phone', v)} onContact={chooseContact} />{contactMessage && <p className="text-[10px] text-muted">{contactMessage}</p>}<ServicePicker values={SPECIALTIES} selected={draft.specialties} onToggle={(v) => update('specialties', draft.specialties.includes(v) ? draft.specialties.filter((x: string) => x !== v) : [...draft.specialties, v])} />{draft.specialties.includes('سایرم') && <TextField label="عنوان سایر تخصص" value={draft.otherSpecialty} onChange={(v) => update('otherSpecialty', v)} placeholder="مثلاً تشریفات یا نورپردازی" />}<button className="btn btn-primary w-full"><Check className="w-4 h-4" /> ذخیره همکار</button></form> : <div className="space-y-3">{items.map((x: ColleagueEntry) => <article key={x.id} className="card p-4"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-surface2 text-gold"><UserRound className="w-5 h-5" /></span><div className="min-w-0 flex-1"><h3 className="text-[15px] font-extrabold">{x.name}</h3><a href={`tel:${x.phone}`} className="mt-1 flex items-center gap-1.5 text-[11px] text-muted"><Phone className="w-3.5 h-3.5 text-gold" />{x.phone}</a></div><button onClick={() => onEdit(x)} className="icon-button !h-9 !w-9"><Pencil className="w-4 h-4" /></button><button onClick={() => onDelete(x)} className="icon-button !h-9 !w-9 text-rose"><Trash2 className="w-4 h-4" /></button></div><div className="mt-3 flex flex-wrap gap-1.5">{[...x.specialties, ...(x.otherSpecialty ? [x.otherSpecialty] : [])].map(s => <span key={s} className="pill !min-h-7 !py-1 !text-[10px]">{s}</span>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><a href={`tel:${x.phone}`} className="btn btn-primary !min-h-10 !text-[11px]"><Phone className="w-3.5 h-3.5" /> تماس</a><a href={`sms:${x.phone}`} className="btn btn-ghost !min-h-10 !text-[11px]">پیامک</a></div></article>)}</div>}</section>;
const MembersPanel: React.FC<any> = ({ members, editing, draft, update, onSave, onStart, onEdit, onDelete, chooseContact, contactMessage, onLedger }) => <section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="text-[15px] font-extrabold">اعضای ثابت آتلیه</h2><p className="mt-1 text-[10px] text-muted">حساب هر اجرا برای هر عضو جداست</p></div>{!editing && <button onClick={onStart} className="btn btn-primary !px-3 !py-2 !text-[11px]"><Plus className="w-4 h-4" /> عضو جدید</button>}</div>{editing || members.length === 0 ? <form onSubmit={onSave} className="affiche-form card space-y-4 p-4"><div className="form-heading"><span className="form-heading-icon"><UserRound className="w-5 h-5" /></span><div><h2 className="text-[16px] font-extrabold">{editing ? 'ویرایش عضو' : 'عضو ثابت جدید'}</h2><p className="mt-1 text-[10px] text-muted">عضو تیم و نقش اصلی او</p></div></div><TextField label="نام عضو" value={draft.name} onChange={(v: string) => update('name', v)} placeholder="مثلاً علی حاتمی" /><ContactField label="شماره تماس" value={draft.phone} onChange={(v) => update('phone', v)} onContact={chooseContact} />{contactMessage && <p className="text-[10px] text-muted">{contactMessage}</p>}<TextField label="نقش یا تخصص اصلی" value={draft.role} onChange={(v) => update('role', v)} placeholder="مثلاً فیلم‌بردار" /><button className="btn btn-primary w-full"><Check className="w-4 h-4" /> ذخیره عضو</button></form> : <div className="space-y-3">{members.map((x: StudioMemberEntry) => <article key={x.id} className="card p-4"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-surface2 text-gold"><UserRound className="w-5 h-5" /></span><div className="min-w-0 flex-1"><h3 className="text-[15px] font-extrabold">{x.name}</h3><p className="mt-1 text-[11px] text-muted">{x.role} · {x.phone}</p></div><button onClick={() => onEdit(x)} className="icon-button !h-9 !w-9"><Pencil className="w-4 h-4" /></button><button onClick={() => onDelete(x)} className="icon-button !h-9 !w-9 text-rose"><Trash2 className="w-4 h-4" /></button></div><button onClick={() => onLedger(x)} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl bg-olive text-paper text-[12px] font-extrabold"><WalletCards className="w-4 h-4" /> حساب این عضو</button></article>)}</div>}</section>;
const ServicePicker: React.FC<{ values: string[]; selected: string[]; onToggle: (v: string) => void }> = ({ values, selected, onToggle }) => <div><span className="label">نوع تخصص</span><div className="service-picker">{values.map(v => <button type="button" key={v} onClick={() => onToggle(v)} className={`service-option ${selected.includes(v) ? 'service-option-on' : ''}`}><span className="service-check">{selected.includes(v) && <Check className="w-3.5 h-3.5" />}</span>{v}</button>)}</div></div>;

const LedgerSheet: React.FC<{
  member: StudioMemberEntry;
  form: { eventName: string; date: string; services: LedgerService[]; transactions: LedgerTransaction[] };
  setForm: React.Dispatch<React.SetStateAction<{ eventName: string; date: string; services: LedgerService[]; transactions: LedgerTransaction[] }>>;
  transaction: { type: 'paid' | 'credit'; amount: string; note: string; date: string };
  setTransaction: React.Dispatch<React.SetStateAction<{ type: 'paid' | 'credit'; amount: string; note: string; date: string }>>;
  toggleService: (name: string) => void;
  updateServiceAmount: (name: string, value: string) => void;
  addTransaction: () => void;
  save: () => void;
  close: () => void;
  previous: MemberLedgerEntry[];
}> = ({ member, form, setForm, transaction, setTransaction, toggleService, updateServiceAmount, addTransaction, save, close, previous }) => {
  const total = form.services.reduce((sum, service) => sum + service.amount, 0);
  const paid = form.transactions.filter(x => x.type === 'paid').reduce((sum, x) => sum + x.amount, 0);
  const credit = form.transactions.filter(x => x.type === 'credit').reduce((sum, x) => sum + x.amount, 0);
  return <div className="fixed inset-0 z-[115] flex items-end justify-center sm:items-center sm:p-3" dir="rtl">
    <button className="absolute inset-0 bg-[oklch(18%_.018_105/.72)]" onClick={close} aria-label="بستن" />
    <section className="relative max-h-[92vh] w-full overflow-y-auto rounded-t-[28px] bg-surface p-4 sm:max-w-lg sm:rounded-[28px]">
      <header className="mb-4 flex items-center gap-3"><button onClick={close} className="icon-button !h-10 !w-10"><ArrowRight className="w-4 h-4" /></button><div><h2 className="text-[17px] font-extrabold">حساب {member.name}</h2><p className="mt-1 text-[10px] text-muted">هر مجلس یک حساب جدا دارد</p></div></header>
      <div className="space-y-4">
        <div className="form-heading"><span className="form-heading-icon"><CreditCard className="w-5 h-5" /></span><div><b>ثبت مجلس جدید</b><p className="mt-1 text-[10px] text-muted">خدمات و مبلغ‌های همین اجرا</p></div></div>
        <TextField label="اسم مجلس" value={form.eventName} onChange={v => setForm(x => ({ ...x, eventName: v }))} placeholder="مثلاً عروسی علی و سارا" />
        <div><span className="label">تاریخ مجلس</span><JalaliDatePicker value={isoJ(form.date)} onChange={value => setForm(x => ({ ...x, date: jalaliToIso(value) }))} /></div>
        <div><span className="label">خدمات ارائه‌شده</span><div className="service-picker">{LEDGER_SERVICES.map(name => { const selected = form.services.some(x => x.name === name); const item = form.services.find(x => x.name === name); return <div key={name} className={`service-money-row ${selected ? 'service-money-row-on' : ''}`}><button type="button" onClick={() => toggleService(name)} className="service-option service-option-compact"><span className="service-check">{selected && <Check className="w-3.5 h-3.5" />}</span>{name}</button>{selected && <input className="field service-money-input" inputMode="numeric" value={moneyInput(item?.amount || 0)} onChange={e => updateServiceAmount(name, e.target.value)} placeholder="مبلغ" />}</div>; })}</div></div>
        <div className="ledger-total"><span>جمع دستمزد این مجلس</span><b>{money(total)} تومان</b></div>
        <div className="ledger-transactions"><div className="flex items-center justify-between"><b className="text-[13px]">دریافتی و بستانکاری</b><span className="text-[10px] text-muted">ثبت دستی</span></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setTransaction(x => ({ ...x, type: 'paid' }))} className={`min-h-10 rounded-xl text-[11px] font-extrabold ${transaction.type === 'paid' ? 'bg-teal text-paper' : 'bg-surface2 text-muted'}`}>دریافتی از عضو</button><button type="button" onClick={() => setTransaction(x => ({ ...x, type: 'credit' }))} className={`min-h-10 rounded-xl text-[11px] font-extrabold ${transaction.type === 'credit' ? 'bg-olive text-paper' : 'bg-surface2 text-muted'}`}>بستانکاری عضو</button></div><div className="grid grid-cols-2 gap-2"><input className="field" inputMode="numeric" value={transaction.amount} onChange={e => setTransaction(x => ({ ...x, amount: e.target.value }))} placeholder="مبلغ" /><input className="field" value={transaction.note} onChange={e => setTransaction(x => ({ ...x, note: e.target.value }))} placeholder="توضیح" /></div><div><span className="label">تاریخ تراکنش</span><JalaliDatePicker value={isoJ(transaction.date)} onChange={value => setTransaction(x => ({ ...x, date: jalaliToIso(value) }))} /></div><button type="button" onClick={addTransaction} className="btn btn-ghost w-full"><Plus className="w-4 h-4 text-gold" /> افزودن تراکنش</button>{form.transactions.map(tx => <div key={tx.id} className="flex items-center justify-between gap-2 rounded-xl bg-surface2 p-2.5 text-[11px]"><span>{tx.type === 'paid' ? 'دریافتی' : 'بستانکاری'}{tx.note ? `، ${tx.note}` : ''}</span><b>{money(tx.amount)} تومان</b></div>)}<div className="grid grid-cols-2 gap-2 text-[11px]"><div className="rounded-xl bg-teal/10 p-3"><span className="text-muted">دریافتی</span><b className="mt-1 block text-teal">{money(paid)} تومان</b></div><div className="rounded-xl bg-olive/10 p-3"><span className="text-muted">بستانکاری</span><b className="mt-1 block text-olive">{money(credit)} تومان</b></div></div></div>
        <button type="button" onClick={save} className="btn btn-primary w-full"><Check className="w-4 h-4" /> ثبت حساب این مجلس</button>
        {previous.length > 0 && <div className="space-y-2 border-t border-line pt-4"><b className="text-[13px]">حساب‌های قبلی</b>{previous.map(item => <div key={item.id} className="rounded-2xl border border-line p-3"><div className="flex justify-between text-[11px]"><span>{item.eventName}</span><span className="text-muted">{isoToJalaliLabel(item.date)}</span></div><div className="mt-2 flex justify-between text-[10px] text-muted"><span>{item.services.map(x => x.name).join('، ')}</span><b>{money(item.services.reduce((s, x) => s + x.amount, 0))} تومان</b></div></div>)}</div>}
      </div>
    </section>
  </div>;
};
